services:
  postgres:
    image: ${POSTGRES_IMAGE:-postgres:15}
    container_name: ${POSTGRES_CONTAINER_NAME:-monanga-db}
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-monanga}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-monangapass}
      POSTGRES_DB: ${POSTGRES_DB:-monanga_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ${POSTGRES_VOLUME_NAME:-postgres_data}:/var/lib/postgresql/data
    healthcheck:
      # Use container env vars ($$ escapes to single $ inside the container)
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: ${PGADMIN_IMAGE:-dpage/pgadmin4}
    container_name: ${PGADMIN_CONTAINER_NAME:-pgadmin}
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@monanga.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
