packages:
  - packages/*
  - apps/*
  - .

engines: {node: '>=18.0.0'}

node-linker: hoisted

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - prisma
  - sharp
  - unrs-resolver

registry: https://registry.npmjs.org/
